/**
 * 
 */
package pxchat.net.tcp;

/**
 * This interface contains the callbacks used to react to events generated by a
 * server and the clients connected to id.
 * 
 * @author Markus Döllinger
 */
public interface TCPServerListener extends TCPClientListener {}
